Working space
tmampa/Responsive-design pull request #3
Opened 2021-03-31 15:32 UTC by tmampa

2021-03-31 18:19 UTC, sinansevgi requested changes
# Status: Changes Required ♻️ 
-----

Hello Team,
Great work so far. But there are some issues you need to take care of.

Kindly check the issues down below
------
## General
 - [x] The TNW logo on the navbar should have a link (a tag).
 - [ ] The TNW logo should be on the leftmost part there is a [margin on yours](https://imgur.com/ymX0Pt5).
 - [ ] [Your writer info section](https://imgur.com/KC1nwOk) of the first article overflowing and not visible please fix this.
 - [ ] The header should stick to the top of the screen when the user scrolls down.
 - [ ] There is a missing red overlay with a gradient in the top half of the first article.
 - [ ] Please remove inline comments from your CSS file.
 - [ ] Live demo link on your readme file doesn't work. Please update it with a working link.
 - [ ] Your page has horizontal scroll (_Most of the websites don’t use horizontal scroll bars and as a visitor, it is not natural to scroll sideways as most of us are used to scrolling up and down. The fact that most mouse scroll only up and down may limit the website user from scrolling sideways_.) (You can easily fix this by adding overflow-x: hidden to your body element. Please make sure all content is visible after setting overflow-x to hidden )

##  Latest Funding Section
- [ ]  The navigation menu should be on the right on [desktop view](https://imgur.com/qDKwXtm). (It should be on the left in tablet view.) 
- [ ] Please group all link items in the navigation menu under the nav tag.
- [ ] [Your section](https://imgur.com/C5xsptv) doesn't match with the [original design](https://imgur.com/qDKwXtm) (Both desktop and mobile). Please check the original design and refactor that section.
- [ ] Two categories items overflowed by previous items please fix this. 
- [ ] Two categories items, should have links.
- [ ] Your section **doesn't have a mobile version or tablet version** at all. Please implement a [mobile version](https://imgur.com/IrfcCXB) and [tablet version](https://imgur.com/stBb587).
While implementing mobile and tablet version please be sure that you fulfill these requirements: :point_down:  
#### Mobile
 - - [ ] The nav menu is below the main title, and the options are aligned in a column
 - - [ ] Each article takes the full width of the screen, and they are aligned in a column
#### Tablet
- - [ ] The nav menu is below the main title, and the options are aligned in a row, separated by |
- - [ ] The first 3 articles appear in a row
#### Desktop
- - [ ] The nav menu is to the left of the main title, and the options are aligned in a row, separated by |
- -  [ ] The first 4 articles appear in a row


## Footer
- [ ] Social media icons are not [centered in link tags](https://imgur.com/KUfn78i)
- [ ] Please group your navigations under the nav tag. (User agents (such as screen readers) that are targeted at users who can benefit from navigation information being omitted in the initial rendering.)
- [ ] Copyright paragraph doesn't match the original design on mobile view.


# "As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 code reviews left for this project."

-----

You can reply to this conversation if you have any questions or need elaboration. :wave: 
Sinan Sevgi

2021-04-02 22:10 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @tmampa & @Loosescrew022 :wave:

__You've really done well so far. Thank you for implementing most of the changes required by the last reviewer :handshake:__

__Your page is looking so good and your responsiveness is sweet :ok_hand: DO NOT GIVE UP: You're almost there :muscle:__

__However, we still have about three(3) changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] We need to ensure that you use HTML5 semantic tags. Please check my inline comments below and fix them as appropriate, and you should be good to go!

**[ OPTIONAL CHANGES ]**

- [ ] Overall, your font size is a bit tiny compared to the size of fonts on the original page. If you're in the mood, I personally recommend you increase the font size a bit.

* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

**REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 1 code review left for this project. If you think that the code review was not fair, you can [request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s).**

_**Please make the required changes and submit another review request when you are done.**_

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-04-02 22:10 UTC, teekaytech commented on index.html
> +		  </ul>
As mentioned by the last reviewer, you have to group your navigations inside the `<nav>` tag. This will ensure that your page is semantically meaningful to the browser  i.e. 
```HTML
<nav>
  <ul class="flex">
    <li><a href="#">Add info</a></li>
    <li id="updates" ><a href="#">Get updates by email</a></li>
    <li><a href="#">See more</a></li>
  </ul>
</nav>
```

2021-04-02 22:10 UTC, teekaytech commented on index.html
> +			  	<img class="logo-img" src="img/tnw-logo.png" alt="TNW logo">
This image (TNW logo) should be a link. i.e. 
```HTML
<a>
  <img class="lo~go-img" src="img/tnw-logo.png" alt="TNW logo">
</a>
```

2021-04-04 00:50 UTC, voscarmv approved these changes
# Project status: Approved 💯 ✨ 😎 👍 

- Great job applying the last required details to your project.

### You may merge this branch and move forward ⛙🛣️ 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-04-04 04:17 UTC, voscarmv requested changes
# Impressive work.  💻 👀 ✨
- Great work structuring the Milestone 2 sections.

## However, there are some changes required 👀 🧰 🔨 🔧
- Your Latest News, Latest Funding, Hard fork, and Latest Deals sections have stretched images on larger monitor sizes. Please fix this:

![image](https://user-images.githubusercontent.com/2739245/113498465-58db3e00-94ca-11eb-9d3c-333d32f430fe.png)


### Submit these changes and request a new code review! 😄 👍

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier)🧑‍💻🗨️🧑‍💻
# Happy Coding! 🧠 ⌨️ 🖱️ 🖥️

2021-04-04 04:57 UTC, descholar-ceo approved these changes
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @tmampa  , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

2021-04-04 04:59 UTC, merged